<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\RushRacing.Core\RushRacing.Core.csproj" />
    <ProjectReference Include="..\RushRacing.Data\RushRacing.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.*" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>bcae6f5c-e19a-4259-aae9-b27e48e09ee3</UserSecretsId>
  </PropertyGroup>

</Project>
